apiVersion: apps/v1
kind: Deployment

metadata:
  name: go-api
  namespace: challenge-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: diegomais/go-api:acf6ec8
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: api-config
          - secretRef:
              name: api-secret
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 400m
            memory: 128Mi
